<?php

namespace App;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

/**
 * No description found in the table comment.
 *
 * Class User
 * @package App\Models
 *
 * @property integer $id
 * @property string $fullname
 * @property string $email
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Role[] $roles
 */
class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'users';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'phone_number',
        'date_of_birth',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function roles()
	{
		return $this->belongsToMany(
			// Model
			'App\Role',
			// Pivot table
			'role_user',
			// "Our" key
			'user_id',
			// "Their" key
			'role_id'
		);
	}

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function shop()
    {
        return $this->hasOne('App\Shop');
    }

    public function addresses()
    {
        return $this->hasMany('App\Address');
    }

    public function cartStorage()
    {
        return $this->hasMany('App\CartStorage');
    }

}
