<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class DetailSewa
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_sewa
 * @property integer $id_kostum
 * @property integer $jumlah_sewa
 * @property string $status
 * @property \Carbon\Carbon $pengambilan
 * @property \Carbon\Carbon $pengembalian
 * @property \Carbon\Carbon $tenggang_kembali
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\HistoriSewa[] $historiSewas
 * @property \App\Models\Kostum $kostum
 * @property \App\Models\Sewa $sewa
 */
class DetailSewa extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'detail_sewa';

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_sewa','id_kostum','jumlah_sewa','status','pemakaian','lama_pemakaian','tenggang_kembali',
    ];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['pengambilan', 'pengembalian', 'tenggang_kembali', 'created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function historiSewas()
	{
		return $this->hasMany(
			// Model
			'App\Models\HistoriSewa',
			// Foreign key
			'id_sewa',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function kostum()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Kostum',
			// Foreign key
			'id',
			// Other key
			'id_kostum'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function sewa()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Sewa',
			// Foreign key
			'id',
			// Other key
			'id_sewa'
		);
	}



}
