<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class DetailBayar
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_bayar
 * @property integer $id_tipe
 * @property integer $status_bayar
 * @property integer $biaya_kirim
 * @property integer $total_bayar
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Rating[] $ratings
 * @property \App\Models\Bayar $bayar
 * @property \App\Models\TipeBayar $tipeBayar
 */
class DetailBayar extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'detail_bayar';


	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function ratings()
	{
		return $this->hasMany(
			// Model
			'App\Models\Rating',
			// Foreign key
			'id_detail_bayar',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function bayar()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Bayar',
			// Foreign key
			'id',
			// Other key
			'id_bayar'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function tipeBayar()
	{
		return $this->belongsTo(
			// Model
			'App\Models\TipeBayar',
			// Foreign key
			'id',
			// Other key
			'id_tipe'
		);
	}



}
