<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class HistoriSewa
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_sewa
 * @property integer $id_kostum
 * @property integer $jumlah_sewa
 * @property string $status
 * @property \Carbon\Carbon $pengambilan
 * @property \Carbon\Carbon $pengembalian
 * @property \Carbon\Carbon $tenggang_kembali
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Kostum $kostum
 * @property \App\Models\DetailSewa $detailSewa
 */
class HistoriSewa extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'histori_sewa';


	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['pengambilan', 'pengembalian', 'tenggang_kembali', 'created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function kostum()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Kostum',
			// Foreign key
			'id',
			// Other key
			'id_kostum'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function detailSewa()
	{
		return $this->belongsTo(
			// Model
			'App\Models\DetailSewa',
			// Foreign key
			'id',
			// Other key
			'id_sewa'
		);
	}



}
