<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class Kostum
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_kategori
 * @property integer $id_toko
 * @property string $nama
 * @property string $deskripsi
 * @property integer $harga
 * @property integer $jumlah_keseluruhan
 * @property integer $jumlah_stok
 * @property integer $rating
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\DetailSewa[] $detailSewas
 * @property \App\Models\HistoriSewa[] $historiSewas
 * @property \App\Models\KostumGambar[] $kostumGambars
 * @property \App\Models\Rating[] $ratings
 * @property \App\Models\Kategori $kategori
 * @property \App\Models\Toko $toko
 */
class KostumDetail extends Model
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'detail_kostum';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_kostum', 'id_ukuran', 'harga', 'jumlah_keseluruhan', 'jumlah_stok',
    ];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];

}
