<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class Sewa
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_toko
 * @property integer $id_pembeli
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Bayar[] $bayars
 * @property \App\Models\Denda[] $dendas
 * @property \App\Models\DetailSewa[] $detailSewas
 * @property \App\Models\Rating[] $ratings
 * @property \App\Models\User $user
 * @property \App\Models\Toko $toko
 */
class Sewa extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'sewa';

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_toko','id_penyewa',
    ];


	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function bayars()
	{
		return $this->hasMany(
			// Model
			'App\Models\Bayar',
			// Foreign key
			'id_sewa',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function dendas()
	{
		return $this->hasMany(
			// Model
			'App\Models\Denda',
			// Foreign key
			'id_sewa',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function detailSewas()
	{
		return $this->hasMany(
			// Model
			'App\Models\DetailSewa',
			// Foreign key
			'id_sewa',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function ratings()
	{
		return $this->hasMany(
			// Model
			'App\Models\Rating',
			// Foreign key
			'id_sewa',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function user()
	{
		return $this->belongsTo(
			// Model
			'App\Models\User',
			// Foreign key
			'id',
			// Other key
			'id_penyewa'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function toko()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Toko',
			// Foreign key
			'id',
			// Other key
			'id_toko'
		);
	}



}
